### ISSUE TITLE
Framework Adoption Status

### ISSUE THREAD

**Issue by tqchen** [dmlc/dlpack#10]
This issue is used to status from framework side on adopting the data structure. So far during GTC @mli have talked to @Yangqing and @soumith and they declared joint effort on this.

## Frameworks on board
- mxnet, pytorch, caffe2, tiny-dnn

## Steps of Adoption
- 1. Data structure adoption, make framework specific Tensor DLTensor compatible
- 2. Operator library isolation
- 3. Possible interpolation between structures

**Comment by tqchen** [comment]
On MXNet side, refactoring of the Tensor Blob data structure to take DLTensor as member starts this week by @ZihengJiang . This will enable mxnet to use function signatures that are DLTensor compatible

**Comment by soumith** [comment]
I can confirm. We are largely happy with dlpack. As we plan out, we will collaborate more on dlpack/tvm.

**Comment by edgarriba** [comment]
Hi, during the summer @Randl will be working on his GSOC project for tiny-dnn doing Tensor refactoring (we decided to adopt xtensor) and GPU integration. It can be a good moment to collaborate with dlpack.

**Comment by naibaf7** [comment]
After talking with Intel (@gongzg), we think that LibDNN will also add dlpack support as a subset of it's parameters and interface to other libraries. It will also add all existing Caffe operators in generative code style.

**Comment by Yangqing** [comment]
Confirming for the Caffe2 adoption.

**Comment by bhack** [comment]
@naibaf7 Can you tell something about the new Intel gpu [opencl kernels](https://github.com/01org/cldnn)?

**Comment by gongzg** [comment]
@bhack I will take care of that. Actually, we have been collaborating internally for a while.

**Comment by bhack** [comment]
@gongzg Have you also collaborated internally with @vpisarev Intel/Opencv team?

**Comment by gongzg** [comment]
@bhack eaxctly, my team work closely with  @vpisarev.

**Comment by bhack** [comment]
@gongzg The Halide effort landed in https://github.com/opencv/opencv_contrib/pull/1186

**Comment by edgarriba** [comment]
@sylvaincorlay you might be interested in this

**Comment by tqchen** [comment]
We created a slack channel for development discussions among the participants of dlpack, send me an email if you are interested in get involved

**Comment by SylvainCorlay** [comment]
@edgarriba @tqchen I would love to join the slack channel thanks for pinging us!

**Comment by garybradski** [comment]
Sure, send an invite.

**Comment by domdivakaruni** [comment]
@tqchen can you send me an invite to the slack channel plz?

**Comment by tqchen** [comment]
just some update here. We released https://github.com/dmlc/tvm yesterday to support dlpack compatible kernel generations for CPU, CUDA, Metal, OpenCL

**Comment by Randl** [comment]
@tqchen any place to start with for C++ interface? All the guides are in python.
