### ISSUE TITLE
Request to release 0.7

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [dmlc/dlpack#107]
Please consider releasing version 0.7 with `kDLOneAPI` added to unblock https://github.com/pytorch/pytorch/pull/78154

@tqchen

**Comment by leofang** [comment]
+1 I've repeatedly requested for this: https://github.com/dmlc/dlpack/pull/101#discussion_r835371495

**Comment by leofang** [comment]
#108

**Comment by oleksandr-pavlyk** [comment]
Thank you @leofang and @tqchen.
