### ISSUE TITLE
Add support to Axelera accelerator

### ISSUE THREAD

**Issue by denizhasan** [dmlc/dlpack#109]
Add new device type to dlpack.h

The device name will be `kDLAxelera` added to DLDeviceType enum

**Comment by denizhasan** [comment]
Hello @tirthasheshpatel I would like to contribute to this issue, how can I gain access? 
Thank you!

**Comment by Yangqing** [comment]
Sorry dlpack is no longer maintained - respectfully removing myself from this thread.

**Comment by tqchen** [comment]
Thanks for chiming in, https://github.com/dmlc/dlpack/pull/122 I think the discussions can follow here. The main rationale is that we will need to wait until the sw stack is being finalized and public, before we can continue to bring the support in
