### ISSUE TITLE
Tag Release 0.1

### ISSUE THREAD

**Issue by tqchen** [dmlc/dlpack#12]
The DLTensor structure is stablized for a while and since one major reason of DLPack is to be used across frameworks, I would recommend we tag release for major ABI version.

The first release is only going to be stable DLTensor structure.

**Comment by bhack** [comment]
What do you think of the new [Openvx plan](https://www.khronos.org/assets/uploads/developers/library/2017-embedded-vision-summit/03_OpenVX-EVA-NN_May17.pdf)?

**Comment by tqchen** [comment]
I think OpenVX is a reasonable blackbox approach.  The pros of these abstraction is that they are encapsulated enough so you can do some interesting optimizations like layout tuning and bit transformation.

The argument against such approach is that this gives the burden of deep learning framework to openvx. In a sense that the run-time need to do things like memory layout transformation, layout tunning, adding more operators, memory management, which becomes a deep learning framework of its own. 

Usually framework developers like more transparency and openness, for example, directly exposing fused kernel and interpolation with OpenCL would be much more favorable, because that allows framework to do some of the stuffs and generate necessary fused kernel with OpenVX

**Comment by bhack** [comment]
Also I think that we could interpret the Openvx plan more in the context of [NNEF](https://www.khronos.org/assets/uploads/developers/library/2017-embedded-vision-summit/07_NNEF-Update-EVS_May17.pdf)

**Comment by tqchen** [comment]
Let us consider tag v0.1 after #14 is merged. So far we have agreement on the DLTensor structure, and we can move forward from here

**Comment by tqchen** [comment]
v0.1 is tagged
