### ISSUE TITLE
Unclear if tensor deleter requires the caller to take the GIL

### ISSUE THREAD

**Issue by pitrou** [dmlc/dlpack#129]
The [C API doc](https://dmlc.github.io/dlpack/latest/c_api.html#_CPPv4N15DLManagedTensor7deleterE) doesn't state whether the `deleter` callback can expect the GIL to be already acquired, or should do it by itself if necessary.

Both the [Numpy](https://github.com/numpy/numpy/blob/a3ec20ab085aaacbaf9e5b17d01f271d328a10cc/numpy/_core/src/multiarray/dlpack.c#L12-L33) and [CuPy](https://github.com/cupy/cupy/blob/73911980e6557435114c71c7d4e4cd9e62cb54a7/cupy/_core/dlpack.pyx#L87-L93) deleter implementations seem to acquire the GIL by themselves, but it would be nice to update the doc to make this requirement clear.

**Comment by leofang** [comment]
I think this is a duplication of #103, see the conclusion there: https://github.com/dmlc/dlpack/issues/103#issuecomment-1104048804. 

Yes, we should update the description to clarify it, since more and more C/C++ projects are adopting.

**Comment by pitrou** [comment]
Oh, nice, thank you (and sorry for the duplicate).
