### ISSUE TITLE
Consider giving Cython example

### ISSUE THREAD

**Issue by pitrou** [dmlc/dlpack#130]
Currently the DLPack spec provides a [PyCapsule destructor example in C](https://dmlc.github.io/dlpack/latest/python_spec.html#implementation), but it doesn't provide a Cython equivalent.

While writing the Cython equivalent of said C code should be relatively straightforward, I notice that the [CuPy implementation of it](https://github.com/cupy/cupy/blob/73911980e6557435114c71c7d4e4cd9e62cb54a7/cupy/_core/dlpack.pyx#L78-L84) isn't actually a straight translation as it doesn't have the `PyErr_Fetch`/`PyErr_Restore` dance around the deletion code. Unless Cython is doing some magic behind the scenes, it seems that perhaps CuPy is incorrect and a sample Cython implementation in the spec would help avoid such issues.

**Comment by seberg** [comment]
Randomly saw it:  TBH, think the `PyErr_Fetch` is just nonsense to begin with this is just a `tp_dealloc` effectively, and `tp_dealloc` doesn't need this.

There is a fun twist here also where the code knows it cannot raise an error, but still decides it should restore an existing one :).

**Comment by pitrou** [comment]
> Randomly saw it: TBH, think the `PyErr_Fetch` is just nonsense to begin with this is just a `tp_dealloc` effectively, and `tp_dealloc` doesn't need this.

Looking at the `PyCapsule` code, I agree that this doesn't seem necessary.

**Comment by pitrou** [comment]
Note that this issue is originally about giving a Cython example, not just the `PyErr_Fetch` question.

**Comment by seberg** [comment]
Yeah, even the remaining error check isn't really necessary but at least it makes some sense for good sport.

Sorry about the `Closes` tag, it may indeed still make sense to add Cython examples.
