### ISSUE TITLE
Circumnavigation in the Python DLPack docs

### ISSUE THREAD

**Issue by pitrou** [dmlc/dlpack#139]
The page https://dmlc.github.io/dlpack/latest/python_spec.html currently lacks a detailed description of the DLPack Python protocol (for example the `__dlpack__` signature). It claims that "More details about the spec can be found under the [Data interchange mechanisms](https://data-apis.org/array-api/latest/design_topics/data_interchange.html#data-interchange) page", so one is tempted to follow through that link. However, the linked page does not provide a detailed description of the Python protocol either, and does not link to the actual [API docs](https://data-apis.org/array-api/latest/API_specification/generated/array_api.array.__dlpack__.html).

**Comment by leofang** [comment]
Apart from full API signatures which I can fix on both sides (make it fully spelled out on the DLPack Python Spec page, and add hyperlinks to the Array API "Data interchange mechanisms" page), what kind of detailed descriptions you think are missing, once you read the four pages (the first two + `__dlpack__`/`__dlpack_device__` docs)?

**Comment by pitrou** [comment]
The `__dlpack__` API doc(s) should be linked directly from the spec pages IMHO. Otherwise it's too easy to get lost.
