### ISSUE TITLE
[RPC] Add Prefix to DLPack device and type Enumerations 

### ISSUE THREAD

**Issue by tqchen** [dmlc/dlpack#19]
Currently, we are using `kFloat`, `kUInt` for types and `kGPU`, `kOpenCL` for device types. 

While these constant are fine if they sit in a standard namespace like mxnet, since DLPack is a global C structure that sits on global namespace, it might make sense to change the naming convention:

- kFloat -> kDLFloat
- kGPU -> kDLGPU

This might help avoid possible namespace conflicts with the existing packages and also makes it clear that constants come from DLPack. This will need an upgrade of the dependent frameworks though, and we would need to tag another release after this change. Possibly with #18 

Any thoughts?

@piiswrong @nouiz @mli @Yangqing @zdevito @bhack

**Comment by prigoyal** [comment]
@tqchen  we recently made this change to the dlpack.h in ATen. Happy to make a PR for that here as well :)

**Comment by nouiz** [comment]
Seem good to me, but it is more @abergeron that have chance of finding
useful comments to this issue and #18

**Comment by abergeron** [comment]
I don't see any issues with this (apart from the obvious upgrade of dependant projects).

**Comment by tqchen** [comment]
@prigoyal can you open a pr for this change?

**Comment by prigoyal** [comment]
certainly, right away!
