### ISSUE TITLE
Operator Interface

### ISSUE THREAD

**Issue by tqchen** [dmlc/dlpack#2]
We have not yet have an example operator interface, I would propose to have a dedicated issue for discussing this. Candidate interface posting is welcomed.

## Current Consensus in Guideline
There are three categories of operators

-  level0: Those that does not requires workspace memory
-  level1: Those that can declare workspace requirement before execution
-  level2:  Those that need a allocator

The former ones can be relaxed to the later ones. In general putting operator into the most restrictive types leaves chances for the user to decide what to do with them. e.g. level 0 and 1 allows static memory planning

## Questions
- Whether allow operator to reject call for given reasons (e.g. I only take compact tensors)
- How to handle context specification and context switch (thread local runtime?)

**Comment by jermainewang** [comment]
Question: is shape/type information included in operator interface? Or even going further, how about other properties like gradient relationship?

**Comment by tqchen** [comment]
shape/types goes into the DLTensor structure, so they are available. Gradient information is beyond scope and relatively independent from calculation they should belong to a separate part(e.g. NNVM, autograd), this RFC is looking for something minimum that can be shared.

**Comment by tqchen** [comment]
@naibaf7 Since you are the one with experience low level dnn library, do you mind start a draft proposal that can become basis of discussion? Thanks

**Comment by bhack** [comment]
Expecially how tuning can impact interfaces

**Comment by naibaf7** [comment]
@tqchen I'll get to it as soon as I have time. I'll receive an ARM dev board in the coming days and will begin some changes in LibDNN also.
What kind of specifications/interfaces should I draft?

**Comment by bhack** [comment]
Imho a good exercise could be to define what are our boundaries against a full approach like [libocca API](http://libocca.org). Need we to introduce/standardize also kernels auto-tunining abstraction?

**Comment by tqchen** [comment]
Currently I assume there is no persistent storage interface yet. Need to be a bit careful here about speed vs generality, since seems the trend is moving toward stateless operator style (as opposed to putting weights in a layer). Still, having a pre-transform function provided by operator might be useful.

I think we can start from whatever proposal we can have and iterate from there.

**Comment by edgarriba** [comment]
as a starting point a list with prospective operators names and a brief definition could be very useful. I let you do this guys since you have more experience in the field

**Comment by bhack** [comment]
@tqchen Are you more oriented on "low level" composable ops interface or ops as high level layer? I.e. I was reading the TensorFlow [semantic](https://www.tensorflow.org/versions/master/experimental/xla/operation_semantics) of HLO IR.

**Comment by tqchen** [comment]
There are two concepts here

- An operator declaration interface, if you want symbolic graph declaration (possibly a jit/compile is needed)
- An operator execution interface, which is needed to executed every ops, including high level composed 

I think we are mainly talking about operator execution interface. Since this is what is eventually needed by every kinds of modes(including jit). The HLO IR like interface actually can be implemented as a separate layer (for example,  with NNVM) and targets the function signature of the execution interface that people use in common

**Comment by bhack** [comment]
So do you think that we need to support KernelManagment API like http://libocca.org/documentation/API/CPP#Device-KernelManagement?

**Comment by tqchen** [comment]
these are also declaration and compilation interface,  I would suggest the first stage of discussion to be focused on execution interface instead.

**Comment by tqchen** [comment]
Another thing to note is thread-safety issue. If we want something like a kernel(with kernel handle) vs a pure function.

Sometimes is quite useful to call a function from multiple threads as long as it is stateless. This is the place where CUDA  actually has a  better interface than OpenCL. OpenCL's kernel is not thread-safe, and gives that burden to the user.

**Comment by bhack** [comment]
@tqchen About the execution priority can we make a little use cases? I.e. Mxnet want to use a caffe2 ops. What are the dependencies involved and integrations steps required to let Mxnet to use an "external" caffe2 op? Will be the ops exposed self contained or create a dependency on the third party framework?

**Comment by tqchen** [comment]
I think ideally the operator pack is a separately self-contained library. I do know what do you mean by execution priority. But normally ops can be lazily initiated by the caller. Operator library can usually be a separately compiled library (e.g. caffe2-ops), which allows both mxnet and caffe2 links to it.

**Comment by bhack** [comment]
For priority I mean what we want to design first. So we are oriented to link and call the execution of compiled ops code. So eventually tuning, compilation and execution will be a resonsability of the target framework lib.

**Comment by tqchen** [comment]
close this for now as it did not yet go anywhere, we can have more specific RFC proposals
