### ISSUE TITLE
Bit-field or simple enum?

### ISSUE THREAD

**Issue by PENGUINLIONG** [dmlc/dlpack#21]
https://github.com/dmlc/dlpack/blob/24b4f92f03fd2a66e7b972d5461db1352cc81efe/include/dlpack/dlpack.h#L38-L47

According to this comment:

```c
// kCPUPinned = kCPU | kGPU 
```

It seems these constants are defined as bit-field flags, and they can be combined with each other. However, if they are bit flags, only one of `kMetal`, `kVPI` and `kROCM` should be setting `0b00001000`. If they are simple enum values, these values shouldn't be logically operated; a piece of description seems better than the comment shown above; and skipped values (5, 6, 7) are misleading.

If they are defined as bit flags, we can combine them together as results of machine capability query. But _currently_ the possibility we use multiple \*PUs (other than CPU+GPU) or APIs in a single NN task is quite low. Maybe in some deep feature extraction tasks it can be helpful.

**Comment by tqchen** [comment]
The initial thought is to make them bit mask. Eventually, we realized that it is a non-goal, but the flags are kept as they are for backward compatibility.

Having bitmask for GPU and CPU is still helpful since most frameworks act upon this

**Comment by PENGUINLIONG** [comment]
I remember that OpenCL also support memory mapping. Is it okay to ignore that?

**Comment by PENGUINLIONG** [comment]
Great! I'm closing this.
