### ISSUE TITLE
Current privileges of dlpack adopters?

### ISSUE THREAD

**Issue by arogozhnikov** [dmlc/dlpack#27]
Hi, I have recently proposed an adoption of dlpack, however I am not sure my arguments are good. 

It would be nice to have some list of advantages for frameworks/libraires who adopted dlpack.

So far I can see:
- passing tensors on various devices (CPU, GPU, NPU?) between DL frameworks (e.g. this works for cupy and pytorch already)
- using optimized operations from TVM (those operate with `DLManagedTensor`)
- can use TensorComprehensions for operations on tensors (questionnable)

Something else?

**Comment by tqchen** [comment]
What you described is a precise set of current benefit, having a common in-memory format helps to enable interpolation between frameworks
