### ISSUE TITLE
Root Discussion Issue

### ISSUE THREAD

**Issue by tqchen** [dmlc/dlpack#3]
This is the root discussion issue for the proposal. I have give most related folks write access to the repo, but let us do it through PR so that they can be reviewed and discussed. Feel free to propose changes

## Items
- [Tensor Structure](https://github.com/dmlc/dlpack/issues/1)
- [Operator Interface](https://github.com/dmlc/dlpack/issues/2)
- DNN Library wrapping?
     - CuDNN
     - MKLDNN
     - libDNN

**Comment by bhack** [comment]
@yaroslavvb Any interest on this?

**Comment by bhack** [comment]
@tqchen It could be nice to have somebody from OpenAI and TF.

**Comment by tqchen** [comment]
I agree, we could cc some related folks in github. Though I am not sure people's interest in this

**Comment by bhack** [comment]
@yaroslavvb is already OpenAI but I don't know if he is directly interested or could suggest us any other nick.
