### ISSUE TITLE
No mention of unit in the description of `strides`

### ISSUE THREAD

**Issue by haowu80s** [dmlc/dlpack#30]
```
  /*!
   * \brief strides of the tensor,
   *  can be NULL, indicating tensor is compact.
   */
  int64_t* strides;
```
Does not say if the strides are in bytes or number of elements.I believe `numpy` uses the former and `pyTorch` uses the latter. There does not seem to be an obvious convention.

**Comment by fdwr** [comment]
@haowu80s : I was about to open this issue too because I couldn't tell from the comment (yeah, PyTorch appears to use bytes from the example I saw, and graphics/video formats use bytes when dealing with stride).
