### ISSUE TITLE
Common CUDA allocator?

### ISSUE THREAD

**Issue by nouiz** [dmlc/dlpack#33]
I’m making this issue here in DLPack, as I do not think of a better place for this. This issue is between many software and as this is the goal of DLPack. So here seem a good place for this issue. If you know of a better place, tell me.

It happen more and more frequently that in one script, multiple software that need the GPU are used. For optimization reasons, they all implement a memory allocator on top of cudamalloc.

Problems:
The fact that there is many memory allocator in the same experiment cause some problems like memory fragmentation.

Possible solution:
The problems could be solved by having all software(or most software) reuse a common allocator.

Do you agree we should spend time on this problem?
Would you agree to use a common allocator if we find a good proposition?
If so, what features do you need for that allocator?
Who else we should contact related to this?

@soumith @mrocklin @sklam

**Comment by nouiz** [comment]
Just a follow up the new CUDA stream ordered allocator is strong candidate for that shared memory allocator: https://developer.nvidia.com/blog/using-cuda-stream-ordered-memory-allocator-part-2/

**Comment by harrism** [comment]
Pytorch now supports custom external allocators, and RAPIDS RMM now provides a PyTorch allocator that can be used with any RMM memory resource. https://github.com/rapidsai/rmm/pull/1168  This now enables all RAPIDS libraries (e.g. cuDF) to share a CUDA memory allocator with PyTorch.
