### ISSUE TITLE
Add Tensor Format option to DLTensor

### ISSUE THREAD

**Issue by ryanolson** [dmlc/dlpack#35]
As a follow-on to Issue #34, I propose the addition of describing the tensor format for the underlying data in the DLTensor struct. 

This option would consume a single byte with one of two possible values: kDLRowMajor or kDLColumnMajor.

**Comment by ryanolson** [comment]
Upon further thought, one can simple infer based on the strides if the underlying format is row/column major.

Unfortunately, that leaves some ambiguity in the reading of the definition of strides which is allowed to be NULL.

```
  /*!
   * \brief strides of the tensor,
   *  can be NULL, indicating tensor is compact.
   */
  int64_t* strides;
```

https://github.com/dmlc/dlpack/blob/master/include/dlpack/dlpack.h#L140-L144

It is important to be specific about the definition of a NULL value for strides.  I don't have a preference here, but we should explicit state that a NULL value indicates a compact row-major (or column-major) tensor.

**Comment by tqchen** [comment]
It is row-major by default, a PR to clarify things will be more than welcomed
