### ISSUE TITLE
Zero-copy conversion from Numpy to DLPack

### ISSUE THREAD

**Issue by junrushao1994** [dmlc/dlpack#37]
Should we put an example somewhere to illustrate that it is trivially easy to borrow numpy NDArrays to DLManagedTensor without copying the content? I happened to be working on this today.

**Comment by tqchen** [comment]
We can have some of that in dlpack/apps

**Comment by junrushao1994** [comment]
Will do

**Comment by junrushao1994** [comment]
#38
