### ISSUE TITLE
[ambiguity] Does DLManagedTensor::deleter delete its function argument?

### ISSUE THREAD

**Issue by junrushao1994** [dmlc/dlpack#39]
It seems to me an undefined behavior in our protocol whether the deleter below deletes `self` as well. The inconsistency causes a recent crash when using MXNet as a backend for DGL, reported by @zheng-da.

https://github.com/dmlc/dlpack/blob/5c792cef3aee54ad8b7000111c9dc1797f327b59/include/dlpack/dlpack.h#L163-L167

I did a quick check and found that the deleters in TVM and DGL do free `self`, but haven't verified it on PyTorch & Chainer side. Could someone help with this issue? Thanks!

**Comment by junrushao1994** [comment]
I sent a fix on the MXNet side that allows both
https://github.com/apache/incubator-mxnet/pull/15016/

**Comment by tqchen** [comment]
The deleter may not its function argument, but simply implies that the DLManagedTensor no longer want the object. The behavior could be decref if self is also reference counted and shared with others, or delete self if self is a new object and DLManagedTensor is the sole older.

**Comment by junrushao1994** [comment]
@tqchen I agree with your points and suggest we explicitly state that in our protocol.

The bug I introduced in MXNet is that I didn't know the deleter will free the opaque pointer, which causes a double free in DGL.

**Comment by junrushao1994** [comment]
For example, the deleter [here](https://github.com/dmlc/dlpack/pull/38/files#diff-7a886c0f01102a8b14bc674a8c12b553R63) doesn't delete the given handle because the handle is transient.

**Comment by tqchen** [comment]
a PR to clarify the protocol is more than welcomed

**Comment by junrushao1994** [comment]
Will do
