### ISSUE TITLE
Specify Python embedding of DLPack tensors

### ISSUE THREAD

**Issue by hawkinsp** [dmlc/dlpack#51]
DLPack only specifies a C++ API, but in practice there's a Python embedding that multiple frameworks support (via Python capsules) that does not seem to be formally specified or standardized.

The protocol seems to be:
* producers embed a `DLPackManagedTensor` as Python capsule with name `"dltensor"`.
* when a consumer consumes a `DLPackManagedTensor`, it renames the capsule to `"used_dltensor"` so the same capsule cannot be consumed twice.
* different frameworks seem to act differently as to how a consumer should treat a capsule destructor. MXNet seems to remove the capsule destructor, but PyTorch seems to leave it alone (I may have misread the code in either of these two cases.) It would be good to clarify what the correct behavior is. For JAX, I chose to remove the capsule destructor.

**Comment by tqchen** [comment]
Thanks @hawkinsp !The protocol is correct. In terms of removal of destructor. PyTorch's destructor checkes the used_dltensor flag before destruction, so the effect is same as destructor removal.

A PR is more than welcomed.

**Comment by hawkinsp** [comment]
There's still an issue I think. Consider the following case:
* Hypothetical framework F provides a capsule with a destructor that does not check the capsule name.
* PyTorch consumes a DLPack, setting the capsule name to `used_dltensor` but leaving the capsule destructor alone.
* You have a potential double free: the tensor may be destroyed once when F's capsule destructor is called, and once when PyTorch's destroys the DL tensor via the callback in `DLManagedTensor`.

So you need at least one of the following rules:
a) frameworks must remove the capsule destructor when consuming a DLPack, or
b) frameworks must check the capsule name matches "dltensor" in their capsule destructors, and otherwise do nothing.

It would probably be good to specify which.

**Comment by tqchen** [comment]
you are right, I think it is probably a good way to specify the deletion of the destructor. To keep behavior compact to the pytorch one, we can recommend the destructor to check the name as well

**Comment by vadimkantorov** [comment]
Also it would be good to have somewhat "recommended" complete ctypes wrapper in the repo. Currently it is partly in the NumPy example.

I made my own in https://github.com/vadimkantorov/pydlpack/blob/master/dlpack.py

**Comment by tqchen** [comment]
This is now part of https://data-apis.org/array-api/latest/design_topics/data_interchange.html

**Comment by eric-wieser** [comment]
The linked page does not specify anything about what the capsule destructor should do. Would it make sense to specify an exact implementation?
```C
static void dlpack_capsule_deleter(PyObject *self){
    if (PyCapsule_IsValid(self, "used_dltensor")) {
        return;
    }
    DLManagedTensor *managed = (DLManagedTensor *)PyCapsule_GetPointer(self, "dltensor");
    if (managed == NULL) {
        return NULL;
    }
    managed->deleter(managed);
}
```
From what I can tell, any other implementation would be one of incorrect / unsafe / equivalent.

**Comment by hameerabbasi** [comment]
> The linked page does not specify anything about what the capsule destructor should do. Would it make sense to specify an exact implementation?
> 
> ```c
> static void dlpack_capsule_deleter(PyObject *self){
>     if (PyCapsule_IsValid(self, "used_dltensor")) {
>         return;
>     }
>     DLManagedTensor *managed = (DLManagedTensor *)PyCapsule_GetPointer(self, "dltensor");
>     if (managed == NULL) {
>         return NULL;
>     }
>     managed->deleter(managed);
> }
> ```
> 
> From what I can tell, any other implementation would be one of incorrect / unsafe / equivalent.

Small correction, the `return NULL;` line should be simply `return;`, since it's a `void` function.

**Comment by vadimkantorov** [comment]
Also, it would be good to not call deleter if it's NULL. This can be for 0-dim tensors.

**Comment by eric-wieser** [comment]
Is a null deleter allowed by the specification? Where even is the specification?

**Comment by hameerabbasi** [comment]
[`PyCapsule`s do not allow a `NULL` as a data pointer. ](https://docs.python.org/3/c-api/capsule.html?highlight=pycapsule#c.PyCapsule_New), so that cannot possibly be correct. I would assume 0-dim tensors to have all related data in the `DLManagedTensor`.

**Comment by vadimkantorov** [comment]
Anyway, depending on data owning scheme, deleter may be null sometimes. If it can't be null, there should be an assert and a nice crash. Otherwise, I hit an access violation.

**Comment by leofang** [comment]
> [`PyCapsule`s do not allow a `NULL` as a data pointer](https://docs.python.org/3/c-api/capsule.html?highlight=pycapsule#c.PyCapsule_New), so that cannot possibly be correct. I would assume 0-dim tensors to have all related data in the `DLManagedTensor`.

@vadimkantorov Even if it's a 0-dim array, `DLManagedTensor` can't possibly be NULL. The proper place to insert a NULL is `DLTensor.data`, so I can't think of a case where you don't wanna deallocate the memory for `DLManagedTensor`.

**Comment by vadimkantorov** [comment]
I'm talking about `deleter` field being null, not `data` field. For me it happened in practice in  https://github.com/pytorch/pytorch/issues/43166 during implementing DLPack for interop of libtorch and .NET.

**Comment by eric-wieser** [comment]
I think there's some confusion here about `managed->deleter` vs `managed`. The latter obviously cannot be null, and I think @vadimkantorov is talking about the former, which seems unspecified.

**Comment by leofang** [comment]
OK thanks for clarifying, I misread it.

**Comment by leofang** [comment]
Though I still think what @hameerabbasi and I said did not contradict --- you got to have filled in something in `managed`, so is it really ok to set `managed->deleter` to NULL?

**Comment by vadimkantorov** [comment]
Even if it's not okay, the reference implementation should better have an assert there to have a nice crash, and not an access violation at destruction time (which is super-hard to debug).

**Comment by vadimkantorov** [comment]
It may be that tensor owner will do all the deletion, and the tensor consumer doesn't have anything to do any cleanup

**Comment by eric-wieser** [comment]
The only way that can work is if the tensor owner outlives the consumer.

Even if there are tensors which do not need deleters, dlpack needs to choose between:

* `deleter` may be null. The consumer is required to check before calling it
* `deleter` may not be null. The producer is responsible for populating it with a no-op deleter if there is nothing to delete.

**Comment by leofang** [comment]
@vadimkantorov's concern is valid -- the header says the `deleter` can be NULL:
https://github.com/dmlc/dlpack/blob/9b6176fdecb55e9bf39b16f08b96913ed3f275b4/include/dlpack/dlpack.h#L189-L192
though as a workaround maybe there's a way to make `deleter` a no-op for such a case?

**Comment by vadimkantorov** [comment]
yep, that's what i propose as well. if deleter is NULL, just don't call it

**Comment by seberg** [comment]
> if there is no way for the caller to provide a reasonable destructor. 

What does that mean?  That the destructor is unnecessary because the object is immortal, or that a destructor *cannot* be provided (i.e. the exporter doesn't _know_ about the ownership)?

If it is the latter, we have no memory ownership model!  And then Python should probably refuse the `DLPackManagedTensor` by default, since such a tensor can only be used safely is the user is aware of the ownership model!

If `NULL` really means *cannot* be provided, then a `no-op_deleter` (which is reasonable), would indicate that the tensor is effectively immortal rather that it has unknown ownership/lifespan.

**Comment by vadimkantorov** [comment]
for me either is fine, but if deleter is expected please standardize some assert or good error message :)

**Comment by eric-wieser** [comment]
I've edited my code above with two corrections:

* The test for `deleter = NULL` - the specification is clear, I just hadn't realized that the spec _was_ the comments in the header file
* Correctly handling in-flight exceptions

Is the deleter permitted to fail (and for example, call `PyErr_SetString`)? If so, the `assert` in my snippet should be replaced with proper handling.

**Comment by leofang** [comment]
Let's continue the discussion on `deleter` (if still needed) to #74.

**Comment by vadimkantorov** [comment]
@tqchen I think very simple pure Python binding code as found in https://github.com/vadimkantorov/pydlpack is still useful for simple usage / usage without NumPy. I propose to include some bindings like this in dlpack repo (e.g. as sample code)

**Comment by aniongithub** [comment]
> @tqchen I think very simple pure Python binding code as found in https://github.com/vadimkantorov/pydlpack is still useful for simple usage / usage without NumPy. I propose to include some bindings like this in dlpack repo (e.g. as sample code)
> 
> https://data-apis.org/array-api/latest/design_topics/data_interchange.html doesn't seem to address this

I agree :100: with this comment. I want to pass a dlpack structure directly between native and Python code for orchestration purposes, the current approach is geared only towards usage for conversions.
