### ISSUE TITLE
A bit more motivation in README?

### ISSUE THREAD

**Issue by arogozhnikov** [dmlc/dlpack#6]
Hi @tqchen, I've tried to follow original discussion mentioned in README, but got lost somewhere in the middle.

Idea of reusing operations across frameworks sounds good, but what is the benefit of this for 
- frameworks developers?
  - will this allow avoid implementing at least part of the operations?
  - is it going to work in BLAS-like way when one backend can be replaced by newer / more efficient or it is up to backends to use implementations from other libraries?
  - will these conventions provide someone a way to write single code (say, for new operation) that can be used by different frameworks?

- final users (I assume here users of DL frameworks, but there are people who use tensor libraries directly)?
  - will user get more operations / better support for hardware?
  - does it require user to manage installed libraries or side-operations will be already included during compilation? 

- what is the relation with non-DL tensor frameworks (Numpy, Blitz++ are examples of such)? Will those be able to use operations from other frameworks? 

Probably pointing in README such potential benefits is a good idea.

**Comment by tqchen** [comment]
I wrote a bit more here https://github.com/dmlc/dlpack/issues/6
