### ISSUE TITLE
[RFC] Rename DLContext to DLDevice

### ISSUE THREAD

**Issue by icemelon9** [dmlc/dlpack#61]
This RFC proposes to rename the `DLContext` to `DLDevice`. `DLContext` indicates a device for Tensor and ops. Two main reasons for this change:

- The "DLContext" name doesn’t intuitively reflect its semantics of a device.
- Mainstream frameworks including [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/device) and [PyTorch](https://pytorch.org/docs/stable/tensor_attributes.html?highlight=device#torch.torch.device) both use `device` to represent the device to run. I think it’d be good that we use similar terminology to reduce the confusion.

This change will require downstream projects to change accordingly. Feel free to bring up your thoughts and concerns.

Meanwhile, we have a similar [RFC](https://discuss.tvm.apache.org/t/rfc-rename-tvmcontext-to-tvmdevice/9090) for the name change in TVM discuss forum.

**Comment by junrushao1994** [comment]
I agree with the name change. `Context` doesn't really mean anything - its meaning varies depending on its context...

However, to keep people aligned well, I think we need to take a gradual approach:
1) Step 1: provide `DLDevice` as an alias type of `DLContext` by `typedef`
2) Step 2: in the next release, exchange `DLDevice` as the name of the struct, and `DLContext` as an alias
3) Step 3: in the next release, emit a deprecation warning if anyone uses `DLContext` via `__attribute__((deprecated)) `
4) Step 4: remove `DLContext` completely.

**Comment by szha** [comment]
While I agree that "context" is often overloaded, the name "device" can also be confusing as sometimes a physical device can be partitioned into smaller units for execution. For example, the MIG support on A100 allows partitioning a GPU into MIG instances that are all backed by the same GPU device.

**Comment by junrushao1994** [comment]
Yeah I agree with @szha...so what will be the best name then?

**Comment by tqchen** [comment]
Given that Pytorch and TensorFlow adopts the term Device I think it might be a good chance for converging from the API compatibility point of view.

Since naming change does not change the underlying ABI layout, change to `DLDevice` and provide type aliasing might be fine. It would be great to create a quick test case if `from_dlpack` function still works  once we upgraded to the new name, while importing from DLPack exported by  say pytorch(which uses the old name). My guess is that unless there is a symbolc conflict, things should work out of box.

**Comment by tqchen** [comment]
cc @kkraus14 @leofang @prigoyal @zdevito @rgommers @oleksandr-pavlyk

**Comment by szha** [comment]
>  I think it might be a good chance for converging from the API compatibility point of view.

I don't yet see an urgent need for dlpack, an exchange format, to converge to the naming from frameworks. After all, DLPack is already integrated in them, and it's not user facing. The motivation of such a change is to avoid confusion, but as I mentioned above, the alternative "device" doesn't seem that much clearer.

I'd be ok with a change like this but I'd prefer to do it for good reasons.

**Comment by junrushao1994** [comment]
First of all, dlpack is going to be user-facing in-memory exchangeable format, so it makes sense to adopt clearer names. I think we all agree on this.

As a data science practitioner and a non-developer, “context” doesn’t really mean anything without having to look up documents, but “device” does mean like CPU/GPU/... that matches our normally understanding. In this particular case, using “device” does make things much clearer.

Therefore,  I support renaming “context” to something better, like “device” (in terms of consistency between frameworks).

Also I agree with @szha that “device” is not a perfect name, so am open to any better proposals.

**Comment by tqchen** [comment]
To specifically address @szha 's point. Given that CUDA already adopts the name `Device`(e.g. cudaSetDevice). I believe the name is less controversial, as the partition can be viewed as "virtualized device".

Given that most of frameworks already choose device as the name, it may not be a bad step to move.

**Comment by leofang** [comment]
Would this break backward compatibility with libraries that are already released with the old DLPack support?

**Comment by tqchen** [comment]
Specifically on backward compatibility. this is something we should test. Given that the structure layout(thus the ABI) does not change. My guess is that it would not, but need to run experiments to confirm @icemelon9 do you run a quick test(e.g. change the name say in TVM and run pytorch dlpack test)

**Comment by leofang** [comment]
Yeah, need to test if old libraries can still work as either a producer or a consumer of the dltensor capsule.

**Comment by kkraus14** [comment]
+1 to renaming to `device` as long as we can come up with something sensible for handling "virtual" devices like MIG partitions mentioned previous.

**Comment by icemelon9** [comment]
I did a quick test in TVM that I changed the `DLContext` to `DLDevice` and the field name from `ctx` to `device` in the class `DLTensor` in the dlpack.
```
diff --git a/include/dlpack/dlpack.h b/include/dlpack/dlpack.h
index d122b09..758f23b 100644
--- a/include/dlpack/dlpack.h
+++ b/include/dlpack/dlpack.h
@@ -33,7 +33,7 @@
 extern "C" {
 #endif
 /*!
- * \brief The device type in DLContext.
+ * \brief The device type in DLDevice.
  */
 typedef enum {
   /*! \brief CPU device */
@@ -71,7 +71,7 @@ typedef struct {
   DLDeviceType device_type;
   /*! \brief The device index */
   int device_id;
-} DLContext;
+} DLDevice;

 /*!
  * \brief The type code options DLDataType.
@@ -131,7 +131,7 @@ typedef struct {
    */
   void* data;
   /*! \brief The device context of the tensor */
-  DLContext ctx;
+  DLDevice device;
   /*! \brief Number of dimensions */
   int ndim;
   /*! \brief The data type of the pointer*/
```

Then I ran the [dlpack](https://github.com/apache/tvm/blob/790344c6ef035947caaaf1cd812ade8d862802aa/tests/python/contrib/test_dlpack.py) test in TVM to test the compatibility between TVM and PyTorch (1.7.1) and the test can still pass.

**Comment by tqchen** [comment]
Thanks @icemelon9 , if that is the case. Then I think we might be able to do a two step change:

- Do the rename, provide DLContext as an alias type of DLDevice by typedef (add attribute deprecated)
- Remove the typedef in the next release

**Comment by tqchen** [comment]
Thanks everyone for discussion so far. Let us leave this thread open for another week, and propose the change

**Comment by leofang** [comment]
> Then I ran the [dlpack](https://github.com/apache/tvm/blob/790344c6ef035947caaaf1cd812ade8d862802aa/tests/python/contrib/test_dlpack.py) test in TVM to test the compatibility between TVM and PyTorch (1.7.1) and the test can still pass.

Thanks @icemelon9. Am I understanding the code you linked to correctly that TVM has the patch applied but PyTorch does not?

**Comment by icemelon9** [comment]
@leofang Yes, I modified the dlpack in the TVM's submodule and recompiled TVM. PyTorch is installed from conda, so it shouldn't have the patch.

**Comment by tqchen** [comment]
Thanks @icemelon9 , do you mind to open a PR to land this proposal?
